version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - GEONODE_LB_HOST_IP=abdterritorios.urosario.edu.co
      - GEONODE_LB_PORT=80
      - SITEURL=http://abdterritorios.urosario.edu.co/
      - ALLOWED_HOSTS=['abdterritorios.urosario.edu.co', ]
      - GEOSERVER_PUBLIC_LOCATION=http://abdterritorios.urosario.edu.co/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://abdterritorios.urosario.edu.co/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=abdterritorios.urosario.edu.co
      - GEONODE_LB_PORT=80
